name: Lint

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: pip install ruff mypy Pillow
      - name: Run ruff
        run: ruff check hacktools tests
      - name: Run mypy
        run: mypy
